### ISSUE TITLE
Couldn't install this package

### ISSUE THREAD

**Issue by r3verser** [brunch/styl-brunch#4]
Hi, when installing, got error, how could ifix it?

```
631 verbose stack ERROR: Repository not found.
631 verbose stack fatal: Could not read from remote repository.
631 verbose stack
631 verbose stack Please make sure you have the correct access rights
631 verbose stack and the repository exists.
631 verbose stack
631 verbose stack     at ChildProcess.exithandler (child_process.js:211:12)
631 verbose stack     at emitTwo (events.js:106:13)
631 verbose stack     at ChildProcess.emit (events.js:191:7)
631 verbose stack     at maybeClose (internal/child_process.js:885:16)
631 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
632 verbose cwd E:\Web\OpenServer\domains\Paper\brunch_test
633 error Windows_NT 6.1.7601
634 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\r3verser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "styl-brunch"
635 error node v7.1.0
636 error npm  v3.10.9
637 error code 128
638 error Command failed: git -c core.longpaths=true clone --template=C:\Users\r3verser\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:paulmillr/rework.git C:\Users\r3verser\AppData\Roaming\npm-cache\_git-remotes\git-github-com-paulmillr-rework-git-dde98ce4
638 error Cloning into bare repository 'C:\Users\r3verser\AppData\Roaming\npm-cache\_git-remotes\git-github-com-paulmillr-rework-git-dde98ce4'...
638 error ERROR: Repository not found.
638 error fatal: Could not read from remote repository.
638 error
638 error Please make sure you have the correct access rights
638 error and the repository exists.
639 error If you need help, you may report this error at:
639 error     <https://github.com/npm/npm/issues>
640 verbose exit [ 1, true ]
```

**Comment by denysdovhan** [comment]
@r3verser hey! Thanks for reporting!

Could you, please, provide me the content of your `package.json` file?
